name: Build
on:
  push:
    branches: [ main ]
jobs:
  deploy:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: npm build
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - run: npm --prefix ui ci
        - run: npm --prefix ui run build --if-present

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Run tests
          run: sbt test

        - name: Docker stage
          run: sbt Docker/stage