name: Fly Deploy
on:
  push:
    branches: [ main ]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: npm build
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - run: npm --prefix ui ci
        - run: npm --prefix ui run build --if-present
        - run: npm --prefix ui test
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
        - name: Run tests
          run: sbt test
        - name: Docker stage
          run: sbt Docker/stage
        - name: Copy fly.toml config to Dockerfile location
          uses: canastro/copy-file-action@master
          with:
            source: "fly.toml"
            target: "target/docker/stage/fly.toml"
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only target/docker/stage
