name: Merge dependency update

on:
  pull_request_target

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: sbt test

  merge:
    name: Merge dependency update
    if: github.actor == 'scala-steward'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: merge PR
        uses: desbo/merge-pr-action@v0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_UPDATE: minor
          MERGE_METHOD: rebase
